require "options"
require "keymaps"
require "Lazy"
require "autocommands"
require "plugconfigs.slanted-gaps"
vim.cmd([[source ~/.config/nvim/plugconfigs/quick-scope.vim]])
vim.cmd([[source ~/.config/nvim/basic-settings.vim]])
vim.cmd([[source ~/.config/nvim/lua/plugconfigs/vista.vim]])
vim.cmd([[source ~/.config/nvim/plugconfigs/vimwiki.vim]])
vim.cmd([[source ~/.config/nvim/plugconfigs/vimtex.vim]])
